"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createBotConnection = exports.handleAttack = exports.defineAttackResult = exports.startGame = exports.defineGameData = exports.createGame = exports.handleWsSendEvent = exports.createRoomWithUser = void 0;
var createNewRoomWithUser_1 = require("./createNewRoomWithUser");
Object.defineProperty(exports, "createRoomWithUser", { enumerable: true, get: function () { return createNewRoomWithUser_1.default; } });
var handleWsEvent_1 = require("./handleWsEvent");
Object.defineProperty(exports, "handleWsSendEvent", { enumerable: true, get: function () { return handleWsEvent_1.default; } });
var createNewGame_1 = require("./createNewGame");
Object.defineProperty(exports, "createGame", { enumerable: true, get: function () { return createNewGame_1.default; } });
var defineGame_1 = require("./defineGame");
Object.defineProperty(exports, "defineGameData", { enumerable: true, get: function () { return defineGame_1.default; } });
var createNewGame_2 = require("./createNewGame");
Object.defineProperty(exports, "startGame", { enumerable: true, get: function () { return createNewGame_2.default; } });
var defineResultAttack_1 = require("./defineResultAttack");
Object.defineProperty(exports, "defineAttackResult", { enumerable: true, get: function () { return defineResultAttack_1.default; } });
var handleAttacks_1 = require("./handleAttacks");
Object.defineProperty(exports, "handleAttack", { enumerable: true, get: function () { return handleAttacks_1.default; } });
var botConnection_1 = require("./botConnection");
Object.defineProperty(exports, "createBotConnection", { enumerable: true, get: function () { return botConnection_1.default; } });
